default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host => onde está o banco de dados?
  # postgres => ulr (nome do service/container dentro do docker-compose)
  # 'postgres' só pode ser acessado pela mesma network do docker
  host: postgres 
  user: postgres    
  password: changeme
  
 
development:
  <<: *default
  database: OneBitExchange_development
 
 
test:
  <<: *default
  database: OneBitExchange_test
 
 
production:
  <<: *default
  database: OneBitExchange_production
  username: OneBitExchange
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>